# Generated by Django 4.1.3 on 2022-12-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loandisbursment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount_contributed', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount_loaned', models.CharField(max_length=255)),
                ('expected_amount_to_be_paid', models.CharField(max_length=255)),
                ('amount_paid', models.CharField(max_length=255)),
                ('balance_carried_forward', models.CharField(max_length=255)),
            ],
        ),
    ]
