# Generated by Django 4.1.3 on 2022-12-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loandisbursment', '0002_wholeaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='date',
            field=models.DateField(default='2022-12-28'),
            preserve_default=False,
        ),
    ]
